name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g bats
      - run: bats -v
  unit-test-setup:
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
